import os
import json
import re
from collections import defaultdict

# Assume these are defined elsewhere or will be generated by other lobes
# For now, let's create dummy structures
JAVA_TEMPLATE = """
package com.example.myapp;

import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {{

    @Override
    protected void onCreate(Bundle savedInstanceState) {{
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        TextView textView = findViewById(R.id.textView);
        // Dynamic content will be populated here based on the generated APK
        textView.setText("Hello from dynamically generated APK!");
    }}
}}
"""

LAYOUT_XML_TEMPLATE = """
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

    <TextView
        android:id="@+id/textView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Default Text"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

</androidx.constraintlayout.widget.ConstraintLayout>
"""

MANIFEST_XML_TEMPLATE = """
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapp">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.MyApp">
        <activity android:name=".MainActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""

GRADLE_PROPERTIES_TEMPLATE = """
org.gradle.jvmargs=-Xmx2048m
"""

BUILD_GRADLE_APP_TEMPLATE = """
plugins {{
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android' // Assuming Kotlin is used, can be adapted for Java
}}

android {{
    compileSdk 33 // Example compile SDK version

    defaultConfig {{
        applicationId "com.example.myapp"
        minSdk 21 // Example minimum SDK version
        targetSdk 33 // Example target SDK version
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }}

    buildTypes {{
        release {{
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }}
    }}
    compileOptions {{
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }}
    kotlinOptions {{
        jvmTarget = '1.8'
    }}
}}

dependencies {{
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.8.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}}
"""

BUILD_GRADLE_PROJECT_TEMPLATE = """
plugins {{
    id 'com.android.application' version '7.4.2' apply false // Example version
    id 'com.android.library' version '7.4.2' apply false // Example version
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false // Example version
}}
"""

SETTINGS_GRADLE_TEMPLATE = """
pluginManagement {{
    repositories {{
        google()
        mavenCentral()
        gradlePluginPortal()
    }}
}}
dependencyResolutionManagement {{
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {{
        google()
        mavenCentral()
    }}
}}
rootProject.name = "MyApp"
include ':app'
"""

class ArabicAPKGear:
    """
    This lobe is responsible for translating the structured Arabic output
    into a basic Android project structure that can be compiled into an APK.
    It creates the necessary directories and template files.
    """

    def __init__(self, output_dir="output_apk"):
        self.output_dir = output_dir
        self.project_name = "MyApp"
        self.package_name = "com.example.myapp"
        self.app_dir = os.path.join(self.output_dir, "app")
        self.main_java_dir = os.path.join(self.app_dir, "src", "main", "java", *self.package_name.split('.'))
        self.res_dir = os.path.join(self.app_dir, "src", "main", "res")
        self.layout_dir = os.path.join(self.res_dir, "layout")
        self.values_dir = os.path.join(self.res_dir, "values")
        self.mipmap_dir = os.path.join(self.res_dir, "mipmap-hdpi") # Example mipmap dir
        self.manifest_dir = os.path.join(self.app_dir, "src", "main")


    def _create_directory(self, dir_path):
        """Creates a directory if it doesn't exist."""
        os.makedirs(dir_path, exist_ok=True)
        print(f"Created directory: {dir_path}")

    def _write_file(self, file_path, content):
        """Writes content to a file."""
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Created file: {file_path}")

    def setup_project_structure(self, app_title="My App", main_activity_text="Dynamic Content"):
        """
        Sets up the basic Android project structure with template files.
        """
        print("\n--- Setting up Android Project Structure ---")
        self._create_directory(self.output_dir)
        self._create_directory(self.app_dir)
        self._create_directory(self.main_java_dir)
        self._create_directory(self.res_dir)
        self._create_directory(self.layout_dir)
        self._create_directory(self.values_dir)
        self._create_directory(self.mipmap_dir) # Create mipmap directory
        self._create_directory(self.manifest_dir)

        # Create build.gradle (app level)
        build_gradle_app_content = BUILD_GRADLE_APP_TEMPLATE.replace("com.example.myapp", self.package_name)
        self._write_file(os.path.join(self.app_dir, "build.gradle"), build_gradle_app_content)

        # Create build.gradle (project level)
        self._write_file(os.path.join(self.output_dir, "build.gradle"), BUILD_GRADLE_PROJECT_TEMPLATE)

        # Create settings.gradle
        settings_gradle_content = SETTINGS_GRADLE_TEMPLATE.replace("MyApp", self.project_name)
        settings_gradle_content = settings_gradle_content.replace("com.example.myapp", self.package_name)
        self._write_file(os.path.join(self.output_dir, "settings.gradle"), settings_gradle_content)

        # Create gradle.properties
        self._write_file(os.path.join(self.output_dir, "gradle.properties"), GRADLE_PROPERTIES_TEMPLATE)

        # Create AndroidManifest.xml
        manifest_content = MANIFEST_XML_TEMPLATE.replace("com.example.myapp", self.package_name)
        manifest_content = manifest_content.replace("@string/app_name", app_title)
        self._write_file(os.path.join(self.manifest_dir, "AndroidManifest.xml"), manifest_content)

        # Create activity_main.xml
        layout_content = LAYOUT_XML_TEMPLATE.replace("Default Text", main_activity_text)
        self._write_file(os.path.join(self.layout_dir, "activity_main.xml"), layout_content)

        # Create MainActivity.java
        java_content = JAVA_TEMPLATE.replace("package com.example.myapp;", f"package {self.package_name};")
        java_content = java_content.replace("textView.setText(\"Hello from dynamically generated APK!\");", f"textView.setText(\"{main_activity_text}\");")
        self._write_file(os.path.join(self.main_java_dir, "MainActivity.java"), java_content)

        # Create dummy mipmap icons (required for a valid build)
        # In a real scenario, these would be actual icon files
        dummy_icon_content = b"\x89PNG\r\n\x1a\n" # Minimal PNG header
        self._write_file(os.path.join(self.mipmap_dir, "ic_launcher.png"), dummy_icon_content)
        self._write_file(os.path.join(self.mipmap_dir, "ic_launcher_round.png"), dummy_icon_content)

        print("\n--- Android Project Structure Setup Complete ---")
        return self.output_dir

    def generate_apk_components_from_arabic(self, arabic_nlp_output):
        """
        Parses structured Arabic NLP output and generates relevant Android components.
        arabic_nlp_output is expected to be a dictionary or a structured format.
        Example:
        {
            "app_name": "تطبيقي العربي",
            "main_activity_title": "شاشة رئيسية",
            "components": [
                {"type": "TextView", "text": "مرحبا بالعالم", "id": "greetingTextView"},
                # More components can be added
            ]
        }
        """
        print("\n--- Generating APK Components from Arabic NLP Output ---")

        app_name = "MyArabicApp"
        main_activity_text = "Welcome"

        if isinstance(arabic_nlp_output, dict):
            app_name = arabic_nlp_output.get("app_name", app_name)
            main_activity_text = arabic_nlp_output.get("main_activity_title", main_activity_text)
            components = arabic_nlp_output.get("components", [])

            # Update main activity text if provided in components
            for comp in components:
                if comp.get("type") == "TextView" and "text" in comp:
                    main_activity_text = comp["text"]
                    break # Assume first TextView text is the main activity display

            # Placeholder for generating more complex UI elements or logic
            # For now, we just use the main activity title for demonstration
            if components:
                print(f"Detected {len(components)} components for the UI.")
                # Future: Parse and generate UI elements based on 'components'

        else:
            print("Invalid Arabic NLP output format. Using default values.")

        # Set up the project structure with the extracted/default information
        self.setup_project_structure(app_title=app_name, main_activity_text=main_activity_text)

        print("\n--- APK Components Generation from Arabic Complete ---")
        return {
            "project_root": self.output_dir,
            "package_name": self.package_name,
            "app_name": app_name
        }

# --- DEMO ---
if __name__ == "__main__":
    # This demo simulates receiving structured output from an Arabic NLP lobe
    # In a real scenario, this would come from Lobe 0_arabic_lobe or a similar module.

    # Example Arabic NLP output simulating a simple app
    sample_arabic_output_1 = {
        "app_name": "تطبيقي الترحيبي",
        "main_activity_title": "أهلاً بك!",
        "components": [
            {"type": "TextView", "text": "مرحبا بالعالم", "id": "greetingTextView"}
        ]
    }

    # Example with minimal structure
    sample_arabic_output_2 = {
        "app_name": "تطبيق بسيط",
        "main_activity_title": "الشاشة الرئيسية",
    }

    # Example of an empty/invalid output
    sample_arabic_output_3 = {}

    arabic_gear = ArabicAPKGear(output_dir="generated_arabic_apk")

    # Demo 1
    print("\n--- DEMO 1: Generating APK with structured Arabic input ---")
    apk_info_1 = arabic_gear.generate_apk_components_from_arabic(sample_arabic_output_1)
    if apk_info_1:
        print(f"Generated APK info: {apk_info_1}")
        print(f"Project structure created at: {apk_info_1['project_root']}")
    else:
        print("Failed to generate APK components for Demo 1.")

    # Demo 2
    print("\n--- DEMO 2: Generating APK with minimal Arabic input ---")
    apk_info_2 = arabic_gear.generate_apk_components_from_arabic(sample_arabic_output_2)
    if apk_info_2:
        print(f"Generated APK info: {apk_info_2}")
        print(f"Project structure created at: {apk_info_2['project_root']}")
    else:
        print("Failed to generate APK components for Demo 2.")

    # Demo 3
    print("\n--- DEMO 3: Generating APK with empty/invalid Arabic input ---")
    apk_info_3 = arabic_gear.generate_apk_components_from_arabic(sample_arabic_output_3)
    if apk_info_3:
        print(f"Generated APK info: {apk_info_3}")
        print(f"Project structure created at: {apk_info_3['project_root']}")
    else:
        print("Failed to generate APK components for Demo 3.")

    print("\n--- ArabicAPKGear Module Demo Finished ---")