import os
import subprocess
from pathlib import Path
import shutil

# Define constants for APK building
ANDROID_SDK_ROOT = os.environ.get("ANDROID_SDK_ROOT")
JAVA_HOME = os.environ.get("JAVA_HOME")

if not ANDROID_SDK_ROOT:
    raise EnvironmentError("ANDROID_SDK_ROOT environment variable is not set.")
if not JAVA_HOME:
    raise EnvironmentError("JAVA_HOME environment variable is not set.")

BUILD_TOOLS_DIR = Path(ANDROID_SDK_ROOT) / "build-tools"
APKS_DIR = Path("generated_apks")
PROJECT_DIR = Path("apk_project")

def get_latest_build_tools_version():
    """Finds the latest installed Android build tools version."""
    build_tools_path = Path(ANDROID_SDK_ROOT) / "build-tools"
    if not build_tools_path.exists():
        raise FileNotFoundError("Android build-tools directory not found.")

    versions = []
    for item in os.listdir(build_tools_path):
        if os.path.isdir(build_tools_path / item):
            versions.append(item)

    if not versions:
        raise FileNotFoundError("No Android build-tools versions found.")

    # Sort versions to get the latest (e.g., '30.0.3' > '29.0.2')
    latest_version = sorted(versions)[-1]
    return build_tools_path / latest_version

# Assume these are generated by previous lobes
GENERATED_ARABIC_CODE = "arabic_source_code_placeholder" # Replace with actual generated code
APP_NAME = "MyAppArabic"
PACKAGE_NAME = "com.example.myapparabic"
VERSION_CODE = "1"
VERSION_NAME = "1.0"


class ApkCompilerLobe:
    """
    Lobe responsible for compiling generated Arabic code into an Android APK.
    This lobe orchestrates the process of setting up a project, compiling,
    and signing the APK.
    """

    def __init__(self):
        self.build_tools_path = get_latest_build_tools_version()
        self.aapt_path = self.build_tools_path / "aapt"
        self.dx_path = self.build_tools_path / "dx"
        self.apksigner_path = self.build_tools_path / "apksigner"
        self.java_exe = Path(JAVA_HOME) / "bin" / "java"

        if not self.aapt_path.exists():
            raise FileNotFoundError(f"aapt not found at {self.aapt_path}")
        if not self.dx_path.exists():
            raise FileNotFoundError(f"dx not found at {self.dx_path}")
        if not self.apksigner_path.exists():
            print(f"Warning: apksigner not found at {self.apksigner_path}. APK will not be signed.")
            self.apksigner_path = None
        if not self.java_exe.exists():
            raise FileNotFoundError(f"java executable not found at {self.java_exe}")

        self.project_root = PROJECT_DIR
        self.output_apk_dir = APKS_DIR
        self.output_apk_path = self.output_apk_dir / f"{APP_NAME}-{VERSION_NAME}.apk"

    def _setup_project_structure(self, arabic_code_content: str):
        """Creates the necessary Android project structure and writes the code."""
        print(f"Setting up project structure in: {self.project_root}")
        if self.project_root.exists():
            shutil.rmtree(self.project_root)
        self.project_root.mkdir(parents=True, exist_ok=True)

        # Create essential Android project directories
        (self.project_root / "res" / "values").mkdir(parents=True, exist_ok=True)
        (self.project_root / "src" / PACKAGE_NAME.replace('.', os.sep)).mkdir(parents=True, exist_ok=True)

        # Create AndroidManifest.xml
        manifest_content = f"""
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="{PACKAGE_NAME}"
    android:versionCode="{VERSION_CODE}"
    android:versionName="{VERSION_NAME}">

    <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="30"/>

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity"
                  android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""
        (self.project_root / "AndroidManifest.xml").write_text(manifest_content)

        # Create strings.xml
        strings_content = f"""
<resources>
    <string name="app_name">{APP_NAME}</string>
</resources>
"""
        (self.project_root / "res" / "values" / "strings.xml").write_text(strings_content)

        # Create layout file (simple example)
        (self.project_root / "res" / "layout").mkdir(parents=True, exist_ok=True)
        layout_content = f"""
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".MainActivity">

    <TextView
        android:id="@+id/main_text"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello from Arabic Generated App!"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="50dp"/>

</LinearLayout>
"""
        (self.project_root / "res" / "layout" / "activity_main.xml").write_text(layout_content)

        # Create Java source file
        java_code_path = self.project_root / "src" / PACKAGE_NAME.replace('.', os.sep) / "MainActivity.java"
        java_code_content = f"""
package {PACKAGE_NAME};

import androidx.appcompat.app.AppCompatActivity;
import android.os.Bundle;
import android.widget.TextView;

public class MainActivity extends AppCompatActivity {{

    @Override
    protected void onCreate(Bundle savedInstanceState) {{
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main); // Link to layout file

        TextView mainText = findViewById(R.id.main_text);
        // Here's where you'd integrate the Arabic code generated by Lobe 0
        // For now, we'll just set a static string
        mainText.setText("{arabic_code_content}");
    }}
}}
"""
        java_code_path.write_text(java_code_content)
        print(f"Project structure created. MainActivity.java written to {java_code_path}")

    def _compile_dex(self):
        """Compiles Java source files into Dalvik Executable (DEX) format."""
        print("\nCompiling Java sources to DEX...")
        dex_file = self.project_root / "classes.dex"

        # Using dx tool from build-tools to convert .class files to .dex
        # This is a simplified approach. A real build would involve javac first.
        # For this example, we assume the Java code is already valid.
        # A more robust solution would use Ant or Gradle.

        # We need to compile the Java code to .class files first, then use dx.
        # For simplicity here, we'll directly use a command that might work if dx
        # can handle source files or if we pre-compile.
        # A more proper way:
        # 1. javac -d classes src/com/example/myapparabic/*.java
        # 2. dx --dex --output=classes.dex classes/
        # Let's simulate by directly calling dx if it can handle source or we have class files.

        # Assuming we have class files in a 'classes' directory for dx
        # Let's create a dummy 'classes' directory and try to compile.
        class_dir = self.project_root / "classes"
        class_dir.mkdir(exist_ok=True)

        # Compile Java to class files
        javac_command = [
            str(Path(JAVA_HOME) / "bin" / "javac"),
            "-d", str(class_dir),
            "-classpath", str(Path(JAVA_HOME) / "lib" / "rt.jar"), # Basic classpath
            str(self.project_root / "src" / PACKAGE_NAME.replace('.', os.sep) / "MainActivity.java")
        ]
        print(f"Running javac: {' '.join(javac_command)}")
        subprocess.run(javac_command, check=True, cwd=self.project_root)

        # Convert class files to DEX
        dx_command = [
            str(self.dx_path),
            "--dex",
            f"--output={dex_file}",
            str(class_dir)
        ]
        print(f"Running dx: {' '.join(dx_command)}")
        subprocess.run(dx_command, check=True, cwd=self.project_root)
        print(f"DEX file generated at: {dex_file}")

    def _build_unsigned_apk(self):
        """Uses AAPT to package resources and the DEX file into an unsigned APK."""
        print("\nBuilding unsigned APK using AAPT...")
        aapt_package_command = [
            str(self.aapt_path),
            "package",
            "-f", # Force overwrite
            "-m", # With the -m option, the command will generate source code for the R.java file
                  # This is useful for making Eclipse project that don't have prebuilt classes.jar
            "-J", str(self.project_root / "src"), # Generate R.java in src
            "-M", str(self.project_root / "AndroidManifest.xml"),
            "-S", str(self.project_root / "res"),
            "-I", str(Path(ANDROID_SDK_ROOT) / "platforms" / "android-30" / "android.jar"), # Target platform
            "-F", str(self.project_root / f"{APP_NAME}-unsigned.apk"), # Output unsigned APK
            "--output-text-encoding", "utf8" # Ensure UTF-8 for Arabic
        ]
        print(f"Running aapt package: {' '.join(aapt_package_command)}")
        subprocess.run(aapt_package_command, check=True, cwd=self.project_root)

        # Now, we need to combine the generated classes.dex with the unsigned APK.
        # AAPT `package` command can also take a library path.
        # Let's re-run `aapt package` with the classes.dex included.
        # This requires the .dex file to be present in a location aapt can find or specified.
        # A more direct way is to use `aapt add` or unzip and re-zip, but `aapt package` can include it.

        # Re-running aapt package to include the classes.dex
        # The `-f` flag is important here.
        final_unsigned_apk_path = self.project_root / f"{APP_NAME}-unsigned.apk"
        aapt_package_command_with_dex = [
            str(self.aapt_path),
            "package",
            "-f",
            "-M", str(self.project_root / "AndroidManifest.xml"),
            "-S", str(self.project_root / "res"),
            "-I", str(Path(ANDROID_SDK_ROOT) / "platforms" / "android-30" / "android.jar"), # Target platform
            f"--main-class={PACKAGE_NAME}.MainActivity", # Specify main activity class
            str(self.project_root / "classes.dex"), # Include the DEX file
            "-F", str(final_unsigned_apk_path),
            "--output-text-encoding", "utf8"
        ]
        print(f"Running aapt package (with DEX): {' '.join(aapt_package_command_with_dex)}")
        subprocess.run(aapt_package_command_with_dex, check=True, cwd=self.project_root)
        print(f"Unsigned APK generated at: {final_unsigned_apk_path}")
        return final_unsigned_apk_path

    def _sign_apk(self, unsigned_apk_path: Path):
        """Signs the APK using a debug keystore."""
        print("\nSigning the APK...")
        if not self.apksigner_path:
            print("Skipping signing as apksigner is not available.")
            return unsigned_apk_path

        # For simplicity, use the default debug keystore.
        # In a real scenario, a custom keystore would be used.
        debug_keystore_path = Path(os.environ.get("HOME", "~")) / ".android" / "debug.keystore"
        if not debug_keystore_path.exists():
            print(f"Debug keystore not found at {debug_keystore_path}. APK will not be signed.")
            return unsigned_apk_path

        signed_apk_path = self.output_apk_path
        apksigner_command = [
            str(self.apksigner_path),
            "sign",
            "--ks", str(debug_keystore_path),
            "--ks-key-alias", "androiddebugkey",
            "--ks-pass", "pass:android", # Default password for debug keystore
            "--key-pass", "pass:android", # Default password for debug keystore
            f"--out={signed_apk_path}",
            str(unsigned_apk_path)
        ]
        print(f"Running apksigner: {' '.join(apksigner_command)}")
        subprocess.run(apksigner_command, check=True, cwd=self.project_root)
        print(f"Signed APK generated at: {signed_apk_path}")
        return signed_apk_path

    def generate_apk(self, arabic_code_content: str):
        """
        Orchestrates the entire APK generation process.
        Args:
            arabic_code_content (str): The generated Arabic code string to be integrated.
        """
        print(f"\n--- Lobe 8_apk_compiler_lobe Starting ---")
        print(f"Target APK: {self.output_apk_path}")

        try:
            # 1. Set up project structure and write code
            self._setup_project_structure(arabic_code_content)

            # 2. Compile Java to DEX
            self._compile_dex()

            # 3. Build unsigned APK using AAPT
            unsigned_apk = self._build_unsigned_apk()

            # 4. Sign the APK
            signed_apk = self._sign_apk(unsigned_apk)

            # Create output directory if it doesn't exist
            self.output_apk_dir.mkdir(parents=True, exist_ok=True)
            # Move the final signed APK to the output directory
            if signed_apk.exists():
                shutil.move(str(signed_apk), str(self.output_apk_path))
                print(f"Final APK moved to: {self.output_apk_path}")
            else:
                print("Error: Signed APK was not created.")


            print(f"\n--- Lobe 8_apk_compiler_lobe Successfully Finished ---")
            return str(self.output_apk_path)

        except FileNotFoundError as e:
            print(f"Dependency not found error: {e}. Make sure JAVA_HOME and ANDROID_SDK_ROOT are set correctly and build tools exist.")
        except subprocess.CalledProcessError as e:
            print(f"Build process failed with return code {e.returncode}.")
            print(f"Command: {e.cmd}")
            print(f"Output: {e.output}")
            print(f"Stderr: {e.stderr}")
        except Exception as e:
            print(f"An unexpected error occurred during APK generation: {e}")
            import traceback
            traceback.print_exc()

        print(f"\n--- Lobe 8_apk_compiler_lobe Finished with Errors ---")
        return None

# Example usage (demonstrating integration logic)
if __name__ == "__main__":
    # This part simulates the output from previous lobes.
    # In a real scenario, `generated_arabic_code` would come from Lobe 0.
    # `generated_arabic_code` should be a string that will be displayed in the app.
    # For this example, we'll use a placeholder that mimics Arabic text.
    simulated_arabic_output = "مرحباً بك في تطبيقنا!" # "Welcome to our application!"

    try:
        compiler = ApkCompilerLobe()
        generated_apk_path = compiler.generate_apk(simulated_arabic_output)

        if generated_apk_path:
            print(f"\nAPK generation complete. APK saved to: {generated_apk_path}")

            # Clean up the temporary project directory
            print("\n--- Cleaning up temporary project directory ---")
            if PROJECT_DIR.exists():
                try:
                    shutil.rmtree(PROJECT_DIR)
                    print(f"Removed temporary project directory: {PROJECT_DIR}")
                except OSError as e:
                    print(f"Error removing directory {PROJECT_DIR}: {e}")
        else:
            print("\nAPK generation failed.")

    except EnvironmentError as e:
        print(f"Configuration error: {e}")
    except FileNotFoundError as e:
        print(f"Initialization error: {e}. Ensure Android SDK and Java are correctly set up.")
    except Exception as e:
        print(f"An unexpected error occurred during the demo: {e}")

    print("\n--- ApkCompilerLobe Demo Finished ---")